#!/usr/bin/env python

import os
import sys

from cafeteira import Cafeteira


def check_superuser():
    if os.geteuid() != 0:
        print "Try to run as Superuser."
        print "e.g.: sudo " + sys.argv[0]
        exit(1)

if __name__ == "__main__":
    check_superuser()
    Cafeteira()
